-- Not using this plugin because this plugin breaks when trying to search for words and the same key pops up as the word you are searching for.
-- return {
--   {
--     'folke/flash.nvim',
--     opts = {
--       modes = {
--         search = {
--           enabled = true,
--         },
--       },
--     },
--   },
-- }
